import { useState } from "react";
import { MapPin, Pencil, Plus, Trash2 } from "lucide-react";

import { createBlock, createDistrict, deleteDistrict, listLocations, updateDistrict } from "../api/locations";
import Button from "../components/ui/Button";
import Loader from "../components/ui/Loader";
import Modal from "../components/ui/Modal";
import { useFetch } from "../hooks/useFetch";

export default function LocationManager() {
  const { data, error, loading, refresh } = useFetch(listLocations); const [editor, setEditor] = useState(null); const [actionError, setActionError] = useState("");
  if (loading && !data) return <Loader />;
  async function save(event) { event.preventDefault(); setActionError(""); try { if (editor.mode === "create") await createDistrict(editor.name); else await updateDistrict(editor.original, { name: editor.name }); setEditor(null); await refresh(); } catch (err) { setActionError(err.message || "Location action failed."); } }
  async function remove(name) { setActionError(""); try { await deleteDistrict(name); await refresh(); } catch (err) { setActionError(err.message || "Location action failed."); } }
  async function addBlock(district) { setActionError(""); try { await createBlock(district, window.prompt("Block name") || "New block"); await refresh(); } catch (err) { setActionError(err.message || "Block records are not available in the existing schema."); } }
  return <div className="grid gap-4"><section className="flex items-center justify-between gap-3 rounded-md border border-slate-200 bg-white p-4 shadow-sm"><div><p className="text-[10px] font-black uppercase tracking-widest text-him-river">Location manager</p><h2 className="mt-1 text-lg font-black text-slate-950">Jan Pukaar selectors</h2></div><Button onClick={() => setEditor({ mode: "create", name: "" })}><Plus className="h-4 w-4" /> District</Button></section>{error && <p className="rounded-md border border-amber-200 bg-amber-50 px-3 py-2 text-xs font-bold text-amber-900">{error}</p>}{actionError && <p className="rounded-md border border-rose-200 bg-rose-50 px-3 py-2 text-xs font-bold text-him-crimson">{actionError}</p>}<div className="grid gap-4 lg:grid-cols-2">{(data || []).map((row) => <article className="rounded-md border border-slate-200 bg-white p-4 shadow-sm" key={row.name}><div className="flex items-start justify-between gap-3"><div><p className="text-[10px] font-black uppercase tracking-widest text-him-river">District</p><h3 className="mt-1 text-lg font-black text-slate-950">{row.name}</h3></div><MapPin className="h-5 w-5 text-him-river" /></div><div className="mt-4 grid gap-2">{(row.blocks || []).map((block) => <div className="rounded-md bg-slate-50 p-3" key={block.name}><p className="text-sm font-black text-slate-900">{block.name}</p><p className="mt-1 text-xs font-medium text-slate-500">{(block.panchayats || []).join(", ") || "No panchayats"}</p></div>)}</div><div className="mt-4 flex flex-wrap gap-2"><Button className="h-8 px-2" onClick={() => setEditor({ mode: "edit", original: row.name, name: row.name })} variant="secondary"><Pencil className="h-3.5 w-3.5" /> Rename</Button><Button className="h-8 px-2" onClick={() => addBlock(row.name)} variant="secondary">Add block</Button><Button className="h-8 px-2" onClick={() => remove(row.name)} variant="danger"><Trash2 className="h-3.5 w-3.5" /></Button></div></article>)}</div>{editor && <Modal onClose={() => setEditor(null)} title={`${editor.mode === "create" ? "Add" : "Rename"} district`}><form className="grid gap-3" onSubmit={save}><input autoFocus className="h-10 rounded-md border border-slate-200 bg-slate-50 px-3 text-sm font-semibold outline-none focus:border-him-river" onChange={(event) => setEditor({ ...editor, name: event.target.value })} placeholder="District name" value={editor.name} /><div className="flex justify-end gap-2"><Button onClick={() => setEditor(null)} variant="secondary">Cancel</Button><Button type="submit">Save</Button></div></form></Modal>}</div>;
}
